"""Returns & cancellations analysis: hand-checked matching, invariants, determinism.

Runs on the shared 1,950-row real fixture plus tiny hand-built frames whose every
number is verifiable with pencil and paper. The fixture is a sparse random sample,
so dataset-specific *magnitudes* are not asserted here -- only the invariants that
must hold for any input, one fully hand-checked matching case, and the determinism
of the CSV deliverable. (Like the cohort tests, there is no full-dataset test here:
the measured full-data headline is reported in the README and regenerated by
`python -m retail --returns`.)
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from retail import clean, exports, ingest, paths, returns
from retail.__main__ import main


# --------------------------------------------------------------------------- #
# Hand-built cases (verifiable with pencil and paper)
# --------------------------------------------------------------------------- #
def _mk(rows) -> pd.DataFrame:
    cols = ["Invoice", "StockCode", "Description", "Quantity", "InvoiceDate", "Price", "CustomerID", "Country"]
    df = pd.DataFrame(rows, columns=cols)
    df["Invoice"] = df["Invoice"].astype(str)
    df["StockCode"] = df["StockCode"].astype(str)
    df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
    df["CustomerID"] = df["CustomerID"].astype("Int64")
    return df


def _hand_case() -> clean.CleanResult:
    # Codes are AA/BB/CC on purpose: single letters like B/D/M/S are reserved
    # bookkeeping codes that the cleaning pipeline strips as non-merchandise.
    rows = [
        # customer 1 buys AA twice, then returns AA -> matches the LATER sale (backward as-of)
        ("100", "AA", "Widget AA", 5, "2011-01-01 09:00", 2.0, 1, "UK"),
        ("101", "AA", "Widget AA", 5, "2011-01-05 09:00", 2.0, 1, "UK"),
        ("C900", "AA", "Widget AA", -5, "2011-01-10 09:00", 2.0, 1, "UK"),   # matched, lag 5 days, value 10
        # customer 1 buys BB but returns CC (never bought) -> identified, unmatched
        ("102", "BB", "Widget BB", 3, "2011-02-01 09:00", 4.0, 1, "UK"),
        ("C901", "CC", "Widget CC", -1, "2011-02-15 09:00", 9.0, 1, "UK"),   # unmatched, value 9
        # customer 2 returns AA with no prior sale -> identified, unmatched, value 4
        ("C902", "AA", "Widget AA", -2, "2011-03-01 09:00", 2.0, 2, "UK"),
        # unidentified return (no CustomerID) -> value 2, never matched
        ("C903", "AA", "Widget AA", -1, "2011-03-05 09:00", 2.0, pd.NA, "UK"),
    ]
    return clean.clean(_mk(rows))


def test_overview_is_hand_checkable():
    c = _hand_case()
    o = returns.returns_overview(c.sales, c.returns)
    # sales: 5*2 + 5*2 + 3*4 = 32 ; returns: 5*2 + 1*9 + 2*2 + 1*2 = 25
    assert o["gross_value"] == pytest.approx(32.0)
    assert o["returned_value"] == pytest.approx(25.0)
    assert o["net_value"] == pytest.approx(7.0)
    assert o["value_return_rate"] == pytest.approx(25.0 / 32.0)
    assert o["return_lines"] == 4
    assert o["cancellation_invoices"] == 4   # C900, C901, C902, C903 are distinct


def test_matching_is_hand_checkable():
    c = _hand_case()
    matched, stats = returns.match_returns_to_sales(c.sales, c.returns)
    assert stats["return_lines"] == 4
    assert stats["identified_lines"] == 3          # C903 has no CustomerID
    assert stats["matched_lines"] == 1             # only customer 1's A-return finds a prior A sale
    assert stats["matched_line_share"] == pytest.approx(0.25)
    assert stats["matched_value_share"] == pytest.approx(0.40)   # 10 of 25
    assert stats["median_lag_days"] == pytest.approx(5.0)        # to the 2011-01-05 sale, not 01-01
    # the matched row is the A return, attributed to the most recent prior sale
    row = matched.iloc[0]
    assert row["StockCode"] == "AA"
    assert row["days_to_return"] == 5.0
    assert row["SaleDate"] == pd.Timestamp("2011-01-05 09:00")


def test_empty_returns_is_handled(cleaned):
    empty = cleaned.returns.iloc[0:0]
    result = returns.run_returns_analysis(cleaned.sales, empty)
    assert result.overview["returned_value"] == 0.0
    assert result.overview["value_return_rate"] == 0.0
    assert result.by_sku.empty
    assert result.match["matched_lines"] == 0
    assert result.concentration["n_returned_skus"] == 0
    assert returns.fig_returns(result) is None       # nothing to plot


# --------------------------------------------------------------------------- #
# Fixture-based invariants
# --------------------------------------------------------------------------- #
@pytest.fixture(scope="module")
def result(cleaned):
    return returns.run_returns_analysis(cleaned.sales, cleaned.returns)


def test_returned_totals_are_consistent(cleaned, result):
    # overview returned value == -sum of the signed returns revenue == sum over the per-SKU table
    signed = float(cleaned.returns["Revenue"].sum())
    assert result.overview["returned_value"] == pytest.approx(-signed)
    assert result.by_sku["returned_value"].sum() == pytest.approx(result.overview["returned_value"])
    assert result.overview["returned_units"] == int(-cleaned.returns["Quantity"].sum())
    # net == gross - returned, exactly
    o = result.overview
    assert o["net_value"] == pytest.approx(o["gross_value"] - o["returned_value"])


def test_by_sku_is_sorted_and_non_negative(result):
    bysku = result.by_sku
    assert (bysku["returned_value"] >= 0).all()
    assert (bysku["returned_units"] >= 0).all()
    assert bysku["returned_value"].is_monotonic_decreasing        # biggest returns first
    # a rate is only defined where the SKU was actually sold; where defined it is >= 0
    defined = bysku["value_return_rate"].notna()
    assert (bysku.loc[defined, "value_return_rate"] >= 0).all()
    assert (bysku.loc[bysku["sold_units"] > 0, "unit_return_rate"].notna()).all()


def test_match_shares_are_bounded(result):
    m = result.match
    assert 0 <= m["matched_lines"] <= m["identified_lines"] <= m["return_lines"]
    assert 0.0 <= m["matched_line_share"] <= 1.0
    assert 0.0 <= m["matched_value_share"] <= 1.0
    if m["matched_lines"]:
        assert m["p25_lag_days"] <= m["median_lag_days"] <= m["p75_lag_days"]
        assert m["median_lag_days"] >= 0.0


def test_lag_buckets_account_for_every_matched_line(result):
    lag = result.lag
    assert list(lag["lag_bucket"]) == [b[0] for b in returns.LAG_BUCKETS]
    assert int(lag["lines"].sum()) == result.match["matched_lines"]
    assert (lag["returned_value"] >= 0).all()
    share = lag["line_share"].sum()
    assert share == pytest.approx(1.0 if result.match["matched_lines"] else 0.0)


def test_monthly_net_is_gross_minus_returned(result):
    mon = result.monthly
    assert {"YearMonth", "gross", "returned", "net", "value_return_rate"} <= set(mon.columns)
    assert np.allclose(mon["net"], mon["gross"] - mon["returned"])
    assert (mon["returned"] >= 0).all()


def test_by_country_rate_is_returned_over_sold(result):
    bc = result.by_country
    assert bc["sold_value"].is_monotonic_decreasing        # top countries by gross first
    assert np.allclose(bc["value_return_rate"], bc["returned_value"] / bc["sold_value"])


def test_concentration_is_a_share(result):
    c = result.concentration
    assert 0.0 <= c["top_n_share"] <= 1.0
    assert c["n_returned_skus"] == len(result.by_sku)
    assert c["skus_to_80pct"] >= 1
    assert c["skus_to_80pct"] <= c["n_returned_skus"]


def test_headline_reports_measured_numbers(result):
    text = returns.headline_text(result)
    assert "returns run at" in text
    assert f"{100 * result.overview['value_return_rate']:.2f}%" in text


# --------------------------------------------------------------------------- #
# Determinism of the deliverable
# --------------------------------------------------------------------------- #
def test_csv_is_byte_identical_on_rerun(result, tmp_path):
    p1 = returns.write_csv(result, out_dir=tmp_path)
    b1 = p1.read_bytes()
    # recompute the analysis independently and rewrite -> identical bytes
    p2 = returns.write_csv(result, out_dir=tmp_path / "again")
    assert p2.read_bytes() == b1
    header = b1.splitlines()[0].decode("utf-8")
    assert header.startswith("StockCode,Description,sold_units,sold_value,returned_units,returned_value")


def test_fig_returns_writes_png(result, tmp_path):
    path = returns.fig_returns(result, out_dir=tmp_path)
    assert path is not None and path.name == "returns_analysis.png"
    assert path.stat().st_size > 10_000


# --------------------------------------------------------------------------- #
# CLI + exports integration
# --------------------------------------------------------------------------- #
def test_cli_returns_skips_gracefully_without_raw_data(monkeypatch, capsys):
    def _absent(force=False):
        raise FileNotFoundError("raw data not downloaded")

    monkeypatch.setattr(ingest, "load_raw", _absent)
    assert main(["--returns"]) == 0
    out = capsys.readouterr().out
    assert "[SKIP]" in out
    assert "download_data.py" in out


def test_cli_returns_runs_on_fixture(monkeypatch, capsys, tmp_path, raw_fixture):
    monkeypatch.setattr(ingest, "load_raw", lambda force=False: raw_fixture.copy())
    monkeypatch.setattr(paths, "FIGURES", tmp_path)
    monkeypatch.setattr(paths, "DELIVERABLES", tmp_path)
    assert main(["--returns"]) == 0
    out = capsys.readouterr().out
    assert "return rate" in out
    assert "[HEADLINE]" in out
    assert (tmp_path / "returns_analysis.png").exists()
    assert (tmp_path / "returns_analysis.csv").exists()


def test_excel_gains_returns_sheet_only_when_present(tmp_path, raw_fixture, cleaned):
    from openpyxl import load_workbook

    from retail import eda

    base = {
        "clean_table": cleaned.report(),
        "monthly": eda.monthly_revenue_table(cleaned.sales),
        "returns_rate": eda.returns_rate_table(cleaned.sales, cleaned.returns),
        "rfm_summary": pd.DataFrame({"Segment": ["Champions"], "Customers": [1], "RevenueShare": [1.0]}),
        "cv": pd.DataFrame({"a": [1]}),
        "cv_summary": pd.DataFrame({"model": ["x"], "mean_mase": [1.0], "worst_mase": [1.0], "fold_wins": [1]}),
        "sku_table": pd.DataFrame({"StockCode": ["1"], "Description": ["d"]}),
        "weekly": eda.monthly_revenue_table(cleaned.sales).set_index("YearMonth")["Revenue"],
    }
    # without a returns_result the sheet must be absent (existing callers are unaffected)
    xlsx_without = exports.export_excel(dict(base), tmp_path / "without.xlsx")
    wb = load_workbook(xlsx_without, read_only=True)
    assert "Returns" not in wb.sheetnames
    wb.close()
    # with one, the Returns sheet appears
    ctx = dict(base)
    ctx["returns_result"] = returns.run_returns_analysis(cleaned.sales, cleaned.returns)
    xlsx_with = exports.export_excel(ctx, tmp_path / "with.xlsx")
    wb = load_workbook(xlsx_with, read_only=True)
    assert "Returns" in wb.sheetnames
    wb.close()
